global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # Sau này bạn sẽ thêm các endpoints của Spring Boot Actuator vào đây